---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --ssh-extra-args="-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=false"
  - ansible-playbook tests/test.yml -i tests/inventory
  - echo "$(<${HOME}/.ansible.cfg)"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
