---

- name: Install Hombrew for package management on macOS.
  git: >
    dest={{ lookup('ENV', 'HOME') }}/.local/brew
    repo=https://github.com/Homebrew/brew.git
    update=no

- name: Install redis for local fact caching.
  package: >
    name=redis
    state=latest
