---
# tasks file for ansible
- name: Generate ansible.cfg
  template:
    src=ansible.cfg.j2
    dest="{{ lookup('env', 'HOME') }}/.ansible.cfg"

- name: Verify Conifguration 
  shell: >
    cat "{{ lookup('env', 'HOME') }}"
