---

- name: Install macOS prerequisites.
  include: macOS.yml
  when: (ansible_distribution == "MacOSX")

- name: Install Ubuntu prerequisites.
  include: ubuntu.yml
  when: (ansible_distribution == "Ubuntu")

- name: Create local installation directories.
  file: >
    path={{ item }}
    state=directory
  with_flattened:
    - "{{opsroll.ansible.install_path}}"
    - "{{opsroll.ansible.group_vars.path}}"
    - "{{opsroll.ansible.host_vars.path}}"
    - "{{opsroll.ansible.inventory.path}}"
    - "{{opsroll.ansible.logs.path}}"
    - "{{opsroll.ansible.playbooks.path}}"
    - "{{opsroll.ansible.plugins.path}}"
    - "{{opsroll.ansible.plugins.action.path}}"
    - "{{opsroll.ansible.plugins.callback.path}}"
    - "{{opsroll.ansible.plugins.connection.path}}"
    - "{{opsroll.ansible.plugins.lookup.path}}"
    - "{{opsroll.ansible.plugins.vars.path}}"
    - "{{opsroll.ansible.plugins.filter.path}}"
    - "{{opsroll.ansible.plugins.test.path}}"
    - "{{opsroll.ansible.plugins.vault.path}}"
    - "{{opsroll.ansible.retry.path}}"
    - "{{opsroll.ansible.roles.galaxy.path}}"
    - "{{opsroll.ansible.roles.local.path}}"
    - "{{opsroll.ansible.vault.path}}"

- name: Generate your default ansible.cfg
  template:
    src=ansible.cfg.j2
    dest="{{ ansible_env.HOME }}/.ansible.cfg"
